// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('front', ['restangular', 'templates-app', 'templates-common', 'front.home', 'ui.state', 'ui.route']).config(function($stateProvider, $urlRouterProvider, RestangularProvider) {
    $urlRouterProvider.otherwise('/home');
    return RestangularProvider.setBaseUrl("/api/");
  }).factory('Event', function(Restangular) {
    return Restangular.all('events/');
  }).controller('AppCtrl', function($scope, Restangular, Event, $log) {
    return $scope.events = Event.customGET();
  });

}).call(this);
