// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('front.home', ['ui.state']).config(function($stateProvider) {
    return $stateProvider.state('home', {
      url: '/home',
      views: {
        "main": {
          controller: 'HomeCtrl',
          templateUrl: 'home/home.tpl.html'
        }
      }
    });
  }).controller('HomeCtrl', function($scope, Event) {});

}).call(this);
